### ISSUE TITLE
sigsegv under ubuntu 

### ISSUE THREAD

**Issue by ofersa** [ipfs-shipyard/git-remote-ipld#23]
Hi,

the push command work perfectly under mac/os and crash under ubuntu.

git push --set-upstream ipld:// master
< capabilities
> push
> fetch
> 
< list for-push
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x76753e]

goroutine 1 [running]:
gx/ipfs/QmabBPe1QjKzxHkvoxZmQJYVGE1FUJXE99pyVnkVemf41z/go-ipfs-api.(*RequestBuilder).Send(0xc0000cd930, 0xd211c0, 0xc0000229b8, 0x10, 0xa57420, 0x1)
	/home/ubuntu/go/src/gx/ipfs/QmabBPe1QjKzxHkvoxZmQJYVGE1FUJXE99pyVnkVemf41z/go-ipfs-api/requestbuilder.go:77 +0x3e
gx/ipfs/QmabBPe1QjKzxHkvoxZmQJYVGE1FUJXE99pyVnkVemf41z/go-ipfs-api.(*RequestBuilder).Exec(0xc0000cd930, 0xd211c0, 0xc0000229b8, 0xa3dda0, 0xc000057c50, 0xc00002c140, 0x40)
	/home/ubuntu/go/src/gx/ipfs/QmabBPe1QjKzxHkvoxZmQJYVGE1FUJXE99pyVnkVemf41z/go-ipfs-api/requestbuilder.go:86 +0x43
gx/ipfs/QmabBPe1QjKzxHkvoxZmQJYVGE1FUJXE99pyVnkVemf41z/go-ipfs-api.(*Shell).ResolvePath(0x0, 0xc00002c140, 0x40, 0xc00002c140, 0x40, 0xc00000c9c0, 0xc0000cda60)
	/home/ubuntu/go/src/gx/ipfs/QmabBPe1QjKzxHkvoxZmQJYVGE1FUJXE99pyVnkVemf41z/go-ipfs-api/shell.go:421 +0x138
main.(*IpnsHandler).List.func1(0xc000060400, 0xc000060400, 0x0)
	/home/ubuntu/go/src/github.com/magik6k/git-remote-ipld/cmd/git-remote-ipld/ipld.go:161 +0xd4
gx/ipfs/QmfRYHUcz9QtXq1KK9dQFqprHcpqCVDjswgZDpbHdTzUUW/go-git.v4/plumbing/storer.(*referenceFilteredIter).ForEach(0xc00000c9e0, 0xc00000ca00, 0x0, 0x0)
	/home/ubuntu/go/src/gx/ipfs/QmfRYHUcz9QtXq1KK9dQFqprHcpqCVDjswgZDpbHdTzUUW/go-git.v4/plumbing/storer/reference.go:82 +0x97
main.(*IpnsHandler).List(0xc000061940, 0xc0001123f0, 0x1, 0xc0000cdd01, 0x1, 0x1, 0x1, 0x0)
	/home/ubuntu/go/src/github.com/magik6k/git-remote-ipld/cmd/git-remote-ipld/ipld.go:158 +0x160
github.com/ipfs-shipyard/git-remote-ipld/core.(*Remote).ProcessCommands(0xc0001123f0, 0xc000061940, 0xd1b320)
	/home/ubuntu/go/src/github.com/ipfs-shipyard/git-remote-ipld/core/remote.go:148 +0x6c1
main.Main(0xc00001e180, 0x3, 0x3, 0xd1b320, 0xc00000e018, 0xd1b340, 0xc00000e020, 0x0, 0xb55270, 0x12)
	/home/ubuntu/go/src/github.com/magik6k/git-remote-ipld/cmd/git-remote-ipld/main.go:39 +0x15f
main.main()
	/home/ubuntu/go/src/github.com/magik6k/git-remote-ipld/cmd/git-remote-ipld/main.go:51 +0x82

**Comment by gerardo-junior** [comment]
+1

**Comment by craigmayhew** [comment]
Also experiencing this under Ubuntu 18.04
golang 1.14

**Comment by craigmayhew** [comment]
Atleast in my case, I fixed this with the following: `ipfs daemon`

I realised that `ipfs daemon` had not been run 🤦 and so the segfault occurs when IPFS is not listening on localhost:5001 (as I was previously running IPFS daemon in a different environment).
