### ISSUE TITLE
README needs adjustments after recent merge

### ISSUE THREAD

**Issue by hoijui** [ipfs-shipyard/git-remote-ipld#25]
it looks liek te hwole install procedure has changed in the last commit, but the README was not updated.
I am a go newb, and can;t figure out myself what I am suposed to do to install now.

**Comment by NatoBoram** [comment]
```bash
GO111MODULE=on make
```

This should make it work its magic. However, the binary is located in `~/go/src/github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld/git-remote-ipld`, so it's not actually installed. They have to fix their build process *and* the `README.md`.

**Comment by hoijui** [comment]
works flawlessly for me, thanks @NatoBoram !

**Comment by Arlodotexe** [comment]
It's been 4 years, we should fix the readme

**Comment by rvagg** [comment]
someone want to PR? I'll merge if someone updates it with something that's working for them

**Comment by ichbestimmtnicht** [comment]
Unfortunatly both of @NatoBoram Workarounds are not working for me.

For the Readme Update: Better not to use "~/go" we have such a nice env var for that $GOPATH
(Homebrew users will be grateful.) 

Log:
```
git clone ipld://2347e110c29742a1783134ef45f5bff58b29e40e
Cloning into '2347e110c29742a1783134ef45f5bff58b29e40e'...
badger 2023/12/15 20:41:27 INFO: All 0 tables opened in 0s
< capabilities
> push
> fetch
> 
< list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x77e2c6]

goroutine 1 [running]:
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Send(0xc000193958, {0x412445?, 0x10?})
	/home/ichbestimmtnicht/go/pkg/mod/github.com/ipfs/go-ipfs-api@v0.0.1/requestbuilder.go:77 +0x26
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Exec(0xc0001939d8?, {0xcc02b0?, 0x10f4200?}, {0x9c9860?, 0xc005536198})
	/home/ichbestimmtnicht/go/pkg/mod/github.com/ipfs/go-ipfs-api@v0.0.1/requestbuilder.go:86 +0x2c
github.com/ipfs/go-ipfs-api.(*Shell).List(0x0, {0x7ffdb33b6d1b, 0x28})
	/home/ichbestimmtnicht/go/pkg/mod/github.com/ipfs/go-ipfs-api@v0.0.1/shell.go:152 +0x110
main.(*IpnsHandler).paths(0x0?, 0x50b060?, {0x7ffdb33b6d1b, 0x28}, 0x0)
	/home/ichbestimmtnicht/go/pkg/mod/github.com/ipfs-shipyard/git-remote-ipld@v0.0.0-20230823083830-8382054dfcd5/cmd/git-remote-ipld/ipld.go:315 +0x53
main.(*IpnsHandler).List(0xc0000c55c0, 0xc0056180e0, 0x0)
	/home/ichbestimmtnicht/go/pkg/mod/github.com/ipfs-shipyard/git-remote-ipld@v0.0.0-20230823083830-8382054dfcd5/cmd/git-remote-ipld/ipld.go:124 +0x145
github.com/ipfs-shipyard/git-remote-ipld/core.(*Remote).ProcessCommands(0xc0056180e0)
	/home/ichbestimmtnicht/go/pkg/mod/github.com/ipfs-shipyard/git-remote-ipld@v0.0.0-20230823083830-8382054dfcd5/core/remote.go:148 +0x762
main.Main({0xc000024150?, 0xc000193f30?, 0x40b32b?}, {0xcbaca0, 0xc000064028}, {0xcbacc0, 0xc000064030}, 0x401750?)
	/home/ichbestimmtnicht/go/pkg/mod/github.com/ipfs-shipyard/git-remote-ipld@v0.0.0-20230823083830-8382054dfcd5/cmd/git-remote-ipld/main.go:39 +0x1e6
main.main()
	/home/ichbestimmtnicht/go/pkg/mod/github.com/ipfs-shipyard/git-remote-ipld@v0.0.0-20230823083830-8382054dfcd5/cmd/git-remote-ipld/main.go:51 +0x4b
```
