### ISSUE TITLE
segfault under Arch Linux

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-shipyard/git-remote-ipld#33]
running --set-upstream on a random repo is causing a sigsegv. Like #23 but in my case under Arch Linux.

```
$ git push --set-upstream ipld:// master
2021/01/25 11:51:11 Replaying from value pointer: {Fid:0 Len:0 Offset:0}
2021/01/25 11:51:11 Iterating file id: 0
2021/01/25 11:51:11 Iteration took: 26.748µs
< capabilities
> push
> fetch
> 
< list for-push
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5577f6a3f820]

goroutine 1 [running]:
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Send(0xc0000c5a08, 0x5577f72ccbe0, 0xc00002aeb0, 0x10, 0x5577f71c61e0, 0x1)
	github.com/ipfs/go-ipfs-api@v0.0.1/requestbuilder.go:77 +0x40
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Exec(0xc0000c5a08, 0x5577f72ccbe0, 0xc00002aeb0, 0x5577f71b2aa0, 0xc000186df0, 0xc000028540, 0x40)
	github.com/ipfs/go-ipfs-api@v0.0.1/requestbuilder.go:86 +0x45
github.com/ipfs/go-ipfs-api.(*Shell).ResolvePath(0x0, 0xc000028540, 0x40, 0xc000028540, 0x40, 0xc0000c5b30, 0x203000)
	github.com/ipfs/go-ipfs-api@v0.0.1/shell.go:330 +0x12b
main.(*IpnsHandler).List.func1(0xc00006c100, 0xc00006c100, 0x0)
	github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld/ipld.go:163 +0xd9
gopkg.in/src-d/go-git.v4/plumbing/storer.(*referenceFilteredIter).ForEach(0xc0001aec60, 0xc0001aec80, 0x0, 0x0)
	gopkg.in/src-d/go-git.v4@v4.11.0/plumbing/storer/reference.go:82 +0xa4
main.(*IpnsHandler).List(0xc00006da80, 0xc000196230, 0x1, 0xc0000c5d01, 0x1, 0x1, 0x1, 0x0)
	github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld/ipld.go:160 +0x13d
github.com/ipfs-shipyard/git-remote-ipld/core.(*Remote).ProcessCommands(0xc000196230, 0xc00006da80, 0x5577f72bfa60)
	github.com/ipfs-shipyard/git-remote-ipld/core/remote.go:148 +0x684
main.Main(0xc000020180, 0x3, 0x3, 0x5577f72bfa60, 0xc000010010, 0x5577f72bfa80, 0xc000010018, 0x0, 0xc00002c0b8, 0x0)
	github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld/main.go:39 +0x17c
main.main()
	github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld/main.go:51 +0x85
```

**Comment by RubenKelevra** [comment]
@magik6k @Stebalien @dirkmc is there still support?

**Comment by aschmahmann** [comment]
No one's really working on this right now, although PRs definitely welcome.

**Comment by RubenKelevra** [comment]
Still happening on the master:

```
badger 2022/05/25 00:40:37 INFO: All 0 tables opened in 0s
< capabilities
> push
> fetch
> 
< list for-push
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55ff93033012]

goroutine 1 [running]:
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Send(0xc000155a70, {0x55ff92cd8707?, 0x10?})
        github.com/ipfs/go-ipfs-api@v0.0.1/requestbuilder.go:77 +0x32
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Exec(0x55ff92d91738?, {0x55ff936a82a0?, 0xc000022f30?}, {0x55ff935c15a0?, 0xc0001c22e0})
        github.com/ipfs/go-ipfs-api@v0.0.1/requestbuilder.go:86 +0x36
github.com/ipfs/go-ipfs-api.(*Shell).ResolvePath(0x0, {0xc0001a0120, 0x57})
        github.com/ipfs/go-ipfs-api@v0.0.1/shell.go:330 +0x113
main.(*IpnsHandler).List.func1(0xc000035880)
        github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld/ipld.go:163 +0xb0
gopkg.in/src-d/go-git.v4/plumbing/storer.(*referenceFilteredIter).ForEach(0xc0001a2258, 0xc0001a2270)
        gopkg.in/src-d/go-git.v4@v4.11.0/plumbing/storer/reference.go:82 +0xd2
main.(*IpnsHandler).List(0xc000035ac0, 0xc00556c150, 0x1)
        github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld/ipld.go:160 +0x12f
github.com/ipfs-shipyard/git-remote-ipld/core.(*Remote).ProcessCommands(0xc00556c150)
        github.com/ipfs-shipyard/git-remote-ipld/core/remote.go:148 +0x442
main.Main({0xc00001e180?, 0xc00002a120?, 0x0?}, {0x55ff936a4608, 0xc00000e010}, {0x55ff936a4628, 0xc00000e018}, 0x0?)
        github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld/main.go:39 +0x1ff
main.main()
        github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld/main.go:51 +0x51
```

**Comment by drgomesp** [comment]
I've opened PR #43 which aims to fix this (at least in a quick and dirty way for now). Can anybody review?
